### ISSUE TITLE
Create option to use an internal cron rather than relying on an external service

### ISSUE THREAD

**Issue by Maelstromeous** [aerotow/eightsleep-nosub-app#4]
Many frameworks allow you to define a crontab expression that runs a particular function.

However since the project is written in NextJS, I don't believe they offer this feature right out of the box. I understand why NextJS was used, it was used for quick and easy deployment to Vercel, but that unfortinately brings limitations.

It may be possible via a Docker implementation to have a script running as a daemon in the background that hits the local API, but that would only be available to Docker installs.

**Comment by aerotow** [comment]
Sort of duplicate to #2. In a Docker Version one can then simply add a SSH/bash script that calls the API Endpoint every 30 minutes.
