### ISSUE TITLE
Cronjob doesn't seem to have any effect on my eight-sleep

### ISSUE THREAD

**Issue by lehighwiz** [aerotow/eightsleep-nosub-app#5]
Hello and thank you so much for creating this application.  I was able to set it up using your instructions easily.  My wife and I were both able to log in to the web app and set our preferences, and the cronjob is set up and running every 30 minutes.  I'm getting a response 200 each time cron runs, but nothing changes... For example, this morning, my eight-sleep is still powered on and running because it was not turned off by the automation, also, the temperatures didn't change through the night.  I'm went through your instructions like 20 times, assuming I missed something, but I can't find anything. Here is what a typical log entry looks like in cronjob when it runs every 30 minutes, yet nothing changes.

<img width="933" alt="image" src="https://github.com/user-attachments/assets/7f3848a3-d8e7-46a4-b5c0-75aa6d007bc4">

**Comment by aerotow** [comment]
Hi,
I fixed one issue in the code this morning which stopped the app from actually changing the pod temperature. Can you try the updated V1.0.2 and let me know if this does the trick for you?
Also, for me to have a look into whats going on I need a screenshot/export of the Logs in your Vercel App. (Make sure to mask your E-Mail Address in the Log)

**Comment by lehighwiz** [comment]
Ok, long story short, there is a single error each for the two users of my eight-sleep each run.  I can post more detailed logs, but there isn't anything interesting other than the below:

`"message": "Invalid enum value. Expected 'warming' | 'cooling' | 'vibration' | 'tapControls', received 'alarms'"`

**Comment by lehighwiz** [comment]
I think this is your huckleberry right here:

https://github.com/aerotow/eightsleep-nosub-app/blob/main/src/server/eight/types.ts#L60

**Comment by aerotow** [comment]
Ah damn. Thats another thing which they must have changed recently. I just changed something related to tempPreference this morning. Give me a few minutes

**Comment by lehighwiz** [comment]
https://github.com/aerotow/eightsleep-nosub-app/pull/6

**Comment by aerotow** [comment]
Thanks! Should be fixed now. See also my comment in #6. Thanks!

**Comment by aerotow** [comment]
Please let me know if this does the trick! Cannot really test it trivially as my Account returns different things

**Comment by lehighwiz** [comment]
i'm trying the change from this morning that you made now.  I'll post here shortly.  Thanks.

**Comment by lehighwiz** [comment]
Yep your change did it.  I just got a clean run, and it did turn off my pod and wife's side as it should have.  Thanks so much.  Nice work!

**Comment by aerotow** [comment]
Amazing! Have a great night! 🎉
