### ISSUE TITLE
Failed to login -- Failed to save login information.

### ISSUE THREAD

**Issue by suedadam** [aerotow/eightsleep-nosub-app#7]
Whenever I try and login I seem to get the error:

```
Database operation failed: error: relation "8slp_users" does not exist
    at /var/task/.next/server/chunks/508.js:10:28957
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E (/var/task/.next/server/app/api/trpc/[trpc]/route.js:1:10274)
    at async /var/task/.next/server/app/api/trpc/[trpc]/route.js:1:6886
    at async a.middlewares (/var/task/.next/server/chunks/406.js:1:78196)
    at async r (/var/task/.next/server/chunks/406.js:1:78502)
    at async r (/var/task/.next/server/chunks/406.js:1:78502)
    at async /var/task/.next/server/app/api/trpc/[trpc]/route.js:1:11326
    at async r (/var/task/.next/server/chunks/406.js:1:78502)
    at async t (/var/task/.next/server/chunks/406.js:1:78844) {
  length: 109,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1449',
  routine: 'parserOpenTable'
}
```

**Comment by sofianathalie** [comment]
Hi! How did you solve it? I've tried changing my password but keep getting the same "authentication failed" message.

**Comment by lezuber** [comment]
Hi,
please try:

Go to Vercel -> Storage -> Select the Postgres DB -> Click "Query" -> Run this query, two lines:
DROP SCHEMA public CASCADE;
then
CREATE SCHEMA public;

If that does not help, go to the Vercel Logs, and paste them into a new issue here. :)

**Comment by sofianathalie** [comment]
I wasn't able to solve it unfortunately... My husband (main user) is able to log in with his credentials, but I am not. I've verified that my email is correctly added to the environment variables. Let me know if you have any other tips in how to solve it!

**Comment by p4vlos** [comment]
@sofianathalie I believe the issue is that once you are not on subscription, 8sleep doesn't allow having 2 sides of the bed. Maybe that is the reason it does not work.
